config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :states

  resources :locations
	  
  resources :articles do
		resources :comments
	end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	http_basic_authenticate_with name: "q", password: "q", except: [:index, :show]

	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
  	@article = Article.find(params[:id])
	end

	def create
  @article = Article.new(article_params)
 
  if @article.save
    redirect_to @article
  else
    render 'new'
  end

  def update
	  @article = Article.find(params[:id])
	 
	  if @article.update(article_params)
	    redirect_to @article
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @article = Article.find(params[:id])
	  @article.destroy
	 
	  redirect_to articles_path
	end
end

	private
		def article_params
			params.require(:article).permit(:title, :text)
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: "q", password: "q", only: :destroy

	def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/locations_controller.rb
require 'yaml'

class LocationsController < ApplicationController

	def index
		@locations = YAML::load(File.open("#{Rails.root.to_s}/config/states.yml"))
		brewery_db = BreweryDB::Client.new do |config|
  		config.api_key = Rails.application.secrets.beer_db_key
		end
		@breweries = Article.all
	end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController

	def index
		@breweries = Article.all
	end

	def show
		@article =  Article.where(text: 'Anchorage')
	end

end

app/controllers/welcome_controller.rb
require 'pry'

class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title, 'Name' %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text, 'Location' %><br>
    <%= f.text_field :text %>
  </p>
 
  <p>
    <%= f.submit 'Save' %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Brewery</h1>

<%= link_to 'Home', root_path %> | 
<%= link_to 'Breweries', articles_path %> | 
<%= link_to 'Cancel', request.referer.present? ? request.referer : default_path %>
 
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing Breweries</h1>
 
<%= link_to 'Home', root_path %> | 
<%= link_to 'New Brewery', new_article_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %> | </td>
      <td><%= link_to 'Edit', edit_article_path(article) %> | </td>
      <td><%= link_to 'Delete', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Brewery</h1>

<%= link_to 'Home', root_path %> | 
<%= link_to 'Breweries', articles_path %> | 
<%= link_to 'Cancel', request.referer.present? ? request.referer : default_path %>

<%= render 'form' %>

app/views/articles/show.html.erb
<%= link_to 'Home', root_path %> | 
<%= link_to 'Breweries', articles_path %> | 
<%= link_to 'New Brewery', new_article_path %> | 
<%= link_to 'Edit', edit_article_path %> |
<%= link_to 'Delete', article_path,
              method: :delete,
              data: { confirm: 'Are you sure?' } %> | 
<%= link_to 'Back', articles_path %>

<p>
  <strong>Name:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Location:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Delete Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CraftBeer360</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<h1>Listing Regions</h1>
 
<%= link_to 'Home', root_path %> | 
<%= link_to 'Breweries', controller: 'articles' %>

<table>
  <tr>
    <th>Region</th>
  </tr>
 
  <% @locations.each do |location| %>
    <tr>
      <td><%= link_to location[1]['name'], state_path(location[1]['name']) %></td>
  <% end %>
</table>

app/views/states/index.html.erb
<h1>Listing Regions</h1>
 
<%= link_to 'Home', root_path %> | 
<%= link_to 'Breweries', controller: 'articles' %>

<table>
  <tr>
    <th>Region</th>
  </tr>
 
  <% @locations.each do |location| %>
    <tr>
      <td><%= link_to location[1]['name'] %></td>
  <% end %>
</table>

app/views/states/show.html.erb
<%= link_to 'Home', root_path %> | 
<%= link_to 'Breweries', articles_path %> | 
<%= link_to 'New Brewery', new_article_path %> | 
<%= link_to 'Edit', edit_article_path %> |
<%= link_to 'Delete', article_path,
              method: :delete,
              data: { confirm: 'Are you sure?' } %> | 
<%= link_to 'Back', articles_path %>


<% @article.each do |brewery| %>
	<p>
	<strong>Name:</strong>
	<%= brewery.title %>
	</p>
	<p>
	<strong>Location:</strong>
	<%= brewery.text %>
	</p>
	<br>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome To Craft Beer 360</h1>
<%= link_to 'Regions', controller: 'locations' %> | 
<%= link_to 'Breweries', controller: 'articles' %> | 
<%= link_to 'New Brewery', new_article_path %>